---

- name: copy mailscript
  copy:
    src: systemd-email
    dest: /usr/local/bin/systemd-email
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: install service file
  template:
    src: status-email-admin@.service.j2
    dest: /etc/systemd/system/status-email-admin@.service
